services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    command: ["mongod", "--replSet", "rs0"]
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_network

  mongo-init-replica:
    image: mongo:latest
    depends_on:
      - mongodb
    entrypoint: ["sh", "-c", "sleep 5 && mongosh --host mongodb_container --eval 'rs.initiate()'"]
    networks:
      - mongo_network

volumes:
  mongodb_data:

networks:
  mongo_network:
    driver: bridge